---
title: "a3-task3-task4-JN"
author: "Jake Nyiri"
date: "10/30/2020"
output: html_document
---

```{r setup, echo=TRUE, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#initial data read-in and librarys
library(tidyverse)
library(here)
library(janitor)
library(lubridate)
library(kableExtra)


raw_urchin_data<-read_csv(here("Data","urchins.csv"))

```

```{r}
#start to initially clean data
cleaned_urchin_data <-raw_urchin_data %>% 
  clean_names() %>% 
  mutate(date=mdy(date))

```

```{r}
#Beginning exploratory visualiztion
#First comparing size distributions between red and pruple urchins


#create histogram of sizedistributions by common name
urchin_hist <-cleaned_urchin_data %>% 
  ggplot(aes(x=size)) +
  geom_histogram()+
facet_wrap(~common_name)

urchin_hist

#create boxplot of same distributions
urchin_box<- cleaned_urchin_data %>% 
  ggplot(aes(x=common_name, y=size))+
  geom_boxplot()

urchin_box

```

```{r}
#rough summary statistics of the urchin data

#Create summary table from urchin data
#for each type of urchin
urchin_summary<-cleaned_urchin_data %>% 
  group_by(common_name) %>% 
  summarize(mean = mean(size),
            median = median(size),
            std_dev = sd(size),
            sample_size = n()) %>% 
  #clean up the appearance of the table
  kable(col.names = c("Common Name",
                      "Mean",
                      "Median", 
                      "Standard Deviation",
                      "Sample size")) %>% 
  kable_styling()
  
 #View the table 
urchin_summary
```


#First thoughts on the data

The size distribution of the purple urchins appears to be skewed towards smaller sizes, with very few larger ones, while the red urchins appear much more normally distributed.

The purple urchins in this sample were also 34% smaller than the red urchins on average.

```{r}
#beginning to explore counts by site and year

#create subset of purple urchins, grouping by year and site

grouped_urchins<-cleaned_urchin_data %>% 
  filter(common_name == "Purple Urchin") %>% 
  mutate(year = year(date)) %>% 
  
  #Create cleaner full-name column of site names
  mutate(site_full = case_when(  
    site=="NAPL"~"Naples Reef",
    site == "CARP"~"Carpenteria Reef",
    site == "AQUE"~"Arroyo Quemado Reef",
    site == "MOHK"~"Mohawk Reef",  # YAY!
    site == "IVEE" ~ "Isla Vista Reef")) %>% 
  
  #group the urchins by site and year and present totals
  group_by(site_full,year) %>% 
  summarize(total_urchins = n()) #%>% 
  
  #clean up the table
  #kable(col.names = c("Site",
                      #"Year",
                      #"Number of Urchins")) %>% 
  #kable_styling()


#View the grouped urchins
grouped_urchins
```

```{r}
#Graphing the grouped urchin data by site and year

purple_urchins_by_site_plot<-grouped_urchins %>% 
  ggplot(aes(x=year, y=total_urchins))+
  geom_bar(stat="identity")+
  facet_wrap(~site_full)

purple_urchins_by_site_plot

```

