---
title: "a3_task4_jake_nyiri"
author: "Jake Nyiri"
date: "11/4/2020"
output: html_document
---

```{r setup, include=FALSE, echo=TRUE, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#load libraries and read-in raw urchin data

library(tidyverse)
library(here)
library(lubridate)
library(janitor)

raw_urchin_data <- read.csv(here("Data", "urchins.csv"))

```


```{r}
#first clean up the dates and names

cleaned_urchin_data <- raw_urchin_data %>%
  clean_names() %>%
  mutate(date=mdy(date)) %>%
  mutate(month=month(date)) %>%
  mutate(year=year(date))

```

```{r}
#Filtering data to obtain purple urchins from Naples Reef in Jan 2010

naples_purple_urchins<-cleaned_urchin_data %>% 
  filter(site == "NAPL" & common_name == "Purple Urchin" &
           month == 1 & year == 2010) %>% 
  group_by(treatment)

#exploratory histogram of size ditributions across the treatments
naples_plot<-naples_purple_urchins %>% 
  ggplot(aes(x=size))+
  geom_histogram(stat="bin", bins=8)+
  facet_wrap(~treatment)

naples_QQ_plot<-naples_purple_urchins %>% 
  ggplot(aes(sample=size))+
  geom_qq()+
  facet_wrap(~treatment)

naples_plot

naples_QQ_plot  
```

The distribution of sizes for both treatments is varied; the annual treatment appears to be bimodal and the control treatment appears more of a comb-type distribution. The angle of the QQ plot for the annual is closer to indicating a normal distribution than that of the control.

```{r}
#summary stats for the urchins by treatment
#they've already been grouped
urchin_summary<-naples_purple_urchins %>% 
  summarize(
    mean = mean(size),
    SD = sd(size),
    sample_size = n())

urchin_summary
```

